-- STU 테이블에서 학번, 이름, 학년, 자신보다 높은 학년의 사람 수
SELECT S1.STUNO, S1.NAME, S1.GRADE, COUNT(S2.GRADE) --> COUNT(나보다 높은 학년의 기준 테이블)
FROM STU S1
LEFT JOIN STU S2 ON S1.GRADE < S2.GRADE --> 조건에 맞지 않는 값도 스스로 카운트 (NULL값들이 JOIN)
--> JOIN은 조건에 맞는 값을 찾는거다 (무조건 '='값만 찾는거는 아님)
GROUP BY S1.STUNO, S1.NAME, S1.GRADE;

-- STUDENT, ENROL, SUBJECT
-- 1. 학생 이름, 학과, 과목명, 점수 출력
SELECT S.STU_NAME, S.STU_DEPT, SJ.SUB_NAME, E.ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SJ ON E.SUB_NO = SJ.SUB_NO;

-- 2. 시험을 안본 학생들은 점수를 0점으로 출력
SELECT S.STU_NAME, S.STU_DEPT, NVL(SJ.SUB_DEPT, '시험 미응시') AS TEST_SUB, NVL(ENR_GRADE, 0) AS GRADE
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
LEFT JOIN SUBJECT SJ ON E.SUB_NO = SJ.SUB_NO;