SELECT *
FROM STUDENT;

-- ORDER BY (정렬)
SELECT *
FROM STUDENT
ORDER BY STU_HEIGHT ASC;    -- 디폴트 : 오름차순(ASC)

SELECT *
FROM STUDENT
ORDER BY STU_HEIGHT DESC;    -- 디폴트 : 내림차순(DESC)

SELECT *
FROM STUDENT
ORDER BY STU_HEIGHT DESC, STU_WEIGHT DESC;  -- 동일한 값의 우선순위


-- STUDENT, ENROL, SUBJECT (JOIN)
SELECT *
FROM ENROL;

SELECT *
FROM STUDENT
INNER JOIN ENROL ON STUDENT.STU_NO = ENROL.STU_NO;

SELECT STU_NAME, ENR_GRADE
FROM STUDENT
INNER JOIN ENROL ON STUDENT.STU_NO = ENROL.STU_NO;

SELECT STU_NAME, ENR_GRADE
FROM STUDENT S      -- 테이블에 별칭 부여
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;

SELECT S.STU_NO, STU_NAME, ENR_GRADE      -- 양 쪽 테이블에 존재하는 컬럼 'STU_NO'을 명확히 구분하기 위해 앞에 테이블의 별칭을 붙임
FROM STUDENT S      
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;


---- ANSI JOIN
--SELECT S.STU_NO, STU_NAME, ENR_GRADE
--FROM STUDENT S      
--INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;

---- ORACLE JOIN
--SELECT S.STU_NO, STU_NAME, ENR_GRADE
--FROM STUDENT S, ENROL E     
--INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;


-- EX) ENROL 테이블 정보 출력할 때, 과목명을 같이 출력 (ENROL과 SUBJECT를 JOIN)
SELECT *
FROM ENROL;
SELECT *
FROM SUBJECT;

SELECT SUB_NAME, E.SUB_NO, STU_NO, ENR_GRADE
FROM ENROL E      
INNER JOIN SUBJECT SJ ON E.SUB_NO = SJ.SUB_NO;  -- 두 테이블의 공통 컬럼 'SUB_NO'를 기준으로 조인

-- EX) 학생이름, 점수 출력
SELECT STU_NAME, ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;

-- EX) 학생 이름, 과목명, 점수 출력
SELECT *
FROM STUDENT;
SELECT *
FROM ENROL;
SELECT *
FROM SUBJECT;

SELECT STU_NAME, ENR_GRADE, SUB_NAME
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SJ ON SJ.SUB_NO = E.SUB_NO;

-- GROUP BY
SELECT AVG(ENR_GRADE), STU_NO
FROM ENROL
GROUP BY STU_NO;    -- GROUP BY를 사용하여 해당 컬럼을 묶어서 계산 가능 (평균 등)

-- EX) 과목별 평균 점수(과목 번호, 평균 점수 출력)
SELECT AVG(ENR_GRADE), SUB_NO
FROM ENROL
GROUP BY SUB_NO;

-- EX) 학생별 평균 점수 (학생 이름, 학과, 평균점수 출력)
SELECT AVG(ENR_GRADE), STU_NAME, STU_DEPT
FROM ENROL E
INNER JOIN STUDENT S ON S.STU_NO = E.STU_NO     -- 공통된 컬럼으로 두 테이블 조인
GROUP BY S.STU_NAME, S.STU_DEPT;                -- 학생 이름, 학과 컬럼을 계산된 평균값과 묶어서 출력

-- EX) 학생들의 전체 평균점수보다 점수가 높은 학생들의 학번, 이름, 점수 출력
SELECT S.STU_NO, S.STU_NAME
FROM STUDENT S;

SELECT *
FROM (
    SELECT AVG(ENR_GRADE) AS ENR_AVG, STU_NO   -- AS 그룹함수 => 그룹함수의 '컬럼화'
    FROM ENROL
    GROUP BY STU_NO
    -- WHERE AVG(ENR_GRADE) > 60   -- 그룹함수는 조건식에 들어갈수 없다
)
WHERE ENR_AVG >= 60;

SELECT *
FROM STUDENT S
INNER JOIN (    -- 서브쿼리가 삽입 가능한 JOIN
    SELECT AVG(ENR_GRADE) AS ENR_AVG, STU_NO   -- AS 그룹함수 => 그룹함수의 '컬럼화'
    FROM ENROL 
    GROUP BY STU_NO
) E ON S.STU_NO = E.STU_NO;


SELECT S.STU_NO, S.STU_NAME, E.ENR_AVG
FROM STUDENT S
INNER JOIN (
    SELECT AVG(ENR_GRADE) AS ENR_AVG, STU_NO
    FROM ENROL
    GROUP BY STU_NO
) E ON S.STU_NO = E.STU_NO;

















