SELECT *
FROM EMP;
SELECT *
FROM DEPT;
SELECT *
FROM SALGRADE;

-- EX) JOB이 MANAGER인 사람들의 평균 급여
SELECT AVG(SAL)
FROM EMP
WHERE JOB = 'MANAGER';

-- EX) 사번, 이름, 사수의 이름을 출력 (셀프 JOIN)
SELECT E.EMPNO, E.ENAME, E2.ENAME   -- SELF JOIN한 테이블의 사원이름 출력
FROM EMP E 
INNER JOIN EMP E2 ON E.MGR = E2.EMPNO;  -- SELF JOIN 방식으로 같은 테이블 내 컬럼을 JOIN

-- EX) 사번, 이름, 부하직원의 수 출력
SELECT COUNT(MGR) AS CNT, MGR
FROM EMP
GROUP BY MGR;

SELECT E.ENAME, E.EMPNO, E2.CNT
FROM EMP E
INNER JOIN (
    SELECT COUNT(MGR) AS CNT, MGR
    FROM EMP
    GROUP BY MGR
) E2 ON E2.MGR = E.EMPNO;






