-- 부서별 평균급여와 전체평균
SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT 부서명, 부서평균
FROM (
    SELECT DNAME AS 부서명, FLOOR(AVG(SAL)) AS 부서평균, 1 AS ORDERKEY
    FROM EMP E
    INNER JOIN DEPT D ON  E.DEPTNO = D.DEPTNO
    GROUP BY DNAME
    UNION
    SELECT 
        '전체평균', FLOOR(AVG(SAL)) AS 전체평균, 2 AS ORDERKEY
    FROM EMP
    GROUP BY '전체평균'
    ORDER BY ORDERKEY, 부서평균 DESC
);

SELECT DNAME, FLOOR(AVG(SAL)) AS 부서평균, 1 AS ORDERKEY
FROM EMP E
INNER JOIN DEPT D ON  E.DEPTNO = D.DEPTNO
GROUP BY DNAME
UNION
SELECT 
    '전체평균', FLOOR(AVG(SAL)) AS 전체평균, 2 AS ORDERKEY
FROM EMP
GROUP BY '전체평균'
ORDER BY ORDERKEY, 부서평균 DESC;


-- 학과별 평균과 전체 평균
SELECT 학과명, 평균점수
FROM (
    SELECT STU_DEPT AS 학과명, AVG(ENR_GRADE) AS 평균점수, 1 AS ORDERKEY
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY STU_DEPT
    UNION
    SELECT '전체평균', ROUND(AVG(ENR_GRADE), 1), 2 AS ORDERKEY
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY '전체평균'
    ORDER BY ORDERKEY, 평균점수 DESC
);

SELECT STU_DEPT AS 학과명, AVG(ENR_GRADE) AS 평균점수, 1 AS ORDERKEY
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_DEPT
UNION
SELECT '전체평균', ROUND(AVG(ENR_GRADE), 1), 2 AS ORDERKEY
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY '전체평균'
ORDER BY ORDERKEY, 평균점수 DESC;

