--6. 96학번과 97학번 중 가장 키가 큰 학생의 학번, 이름, 아이디, 키를 출력하시오.
-- (학번 : STUNO 의 첫 두글자)
SELECT S1.STUNO, S1.NAME, S1.ID, S2.HEIGHT
FROM STU S1
INNER JOIN (
    SELECT SUBSTR(STUNO, 0, 2) AS STUNO, MAX(HEIGHT) AS HEIGHT
    FROM STU
    WHERE SUBSTR(STUNO, 0, 2) = 96 OR SUBSTR(STUNO, 0, 2) = 97
    GROUP BY SUBSTR(STUNO, 0, 2)
) S2 ON S1.HEIGHT = S2.HEIGHT;

SELECT SUBSTR(STUNO, 0, 2) AS STUNO, MAX(HEIGHT) AS HEIGHT
FROM STU
WHERE SUBSTR(STUNO, 0, 2) = 96 OR SUBSTR(STUNO, 0, 2) = 97
GROUP BY SUBSTR(STUNO, 0, 2);