-- 프로시저 호출 시 SELECT 데이터가 여러개일 경우
-- 10번 부서 사람들의 사번, 이름, 급여
EXECUTE DEPT_LIST(10);
CREATE OR REPLACE PROCEDURE  DEPT_LIST
    (P_DEPTNO IN EMP.DEPTNO%TYPE)
IS
    TYPE EMPNO_TABLE IS TABLE OF EMP.EMPNO%TYPE
    INDEX BY BINARY_INTEGER;
    TYPE ENAME_TABLE IS TABLE OF EMP.ENAME%TYPE
    INDEX BY BINARY_INTEGER;
    TYPE SAL_TABLE IS TABLE OF EMP.SAL%TYPE
    INDEX BY BINARY_INTEGER;    -- SQL 내 배열선언
    
    EMPNO_TAB EMPNO_TABLE;
    ENAME_TAB ENAME_TABLE;
    SAL_TAB SAL_TABLE;
BEGIN
    SELECT EMPNO, ENAME, SAL
    FROM EMP
    WHERE DEPTNO = P_DEPTNO;
END;
/