SELECT * FROM BOOK;
SELECT * FROM CUSTOMER;
SELECT * FROM ORDERS;

-- EX) 책 구매자, 구매한 책 이름, 구매 날짜 출력
SELECT C.NAME, B.BOOKNAME, O.ORDERDATE
FROM CUSTOMER C
INNER JOIN ORDERS O ON O.CUSTID = C.CUSTID
INNER JOIN BOOK B ON B.BOOKID = O.BOOKID;