-- EX) 1번 댓글
SELECT C.* 
FROM TBL_BOARD B
INNER JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
WHERE B.BOARDNO = 1;

-- EX) 1번 게시글에 대한 댓글 수
SELECT COUNT(*)
FROM TBL_BOARD B
INNER JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY B.BOARDNO;
-- 각 게시글에 대한 댓글이 출력

-- EX) 게시글 번호, 제목, 내용, 댓글 개수를 출력
SELECT B.BOARDNO, TITLE, CONTENTS, CNT
FROM TBL_BOARD B
INNER JOIN (
SELECT COUNT(*) AS CNT, B.BOARDNO
    FROM TBL_BOARD B
    INNER JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
    GROUP BY B.BOARDNO
) C ON B.BOARDNO = C.BOARDNO;


-- LEFT JOIN (예시)
SELECT B.BOARDNO, TITLE, CONTENTS, NVL(CNT, 0)
FROM TBL_BOARD B
LEFT JOIN (
SELECT COUNT(*) AS CNT, B.BOARDNO
    FROM TBL_BOARD B
    INNER JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
    GROUP BY B.BOARDNO
) C ON B.BOARDNO = C.BOARDNO;



SELECT * FROM TBL_COMMENT;
SELECT * FROM TBL_BOARDFILE;    -- 데이터 없음