SELECT * FROM EMP
WHERE EMPNO = '7369';

-- SELF JOIN
SELECT E1.ENAME, E2.ENAME
FROM EMP E1                                 -- 기준점 테이블
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO      -- SELF JOIN
WHERE E1.EMPNO = '7369';

-- EX) 사번, 이름, 직급, 사수의 이름 출력
SELECT E1.EMPNO AS 사번, E1.ENAME AS 사원, E1.JOB AS 직급, E2.ENAME AS 사수자
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;