SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;

-- 1. 2000이상 급여를 받는 사람의 수를 구하시오
SELECT COUNT(*)
FROM EMP
WHERE SAL >= 2000;

-- 2. 사원번호, 이름, 급여를 출력하시오. 단, 급여를 출력할 때, 
--    커미션을 받는 사람은 커미션과 더해서 출력할 것.
SELECT EMPNO, ENAME, SAL+NVL(COMM, 0) AS SAL
FROM EMP;

-- 3. WARD보다 많은 급여(SAL)을 받는 사람들을 출력하시오.
SELECT ENAME, SAL
FROM EMP
WHERE ENAME = 'WARD';

SELECT ENAME, SAL
FROM EMP
WHERE (
    SELECT SAL
    FROM EMP
    WHERE ENAME = 'WARD'
) < SAL
ORDER BY SAL DESC;

-- 4. 급여등급이 3등급 이상인 사람들의 수를 출력하시오.
SELECT COUNT(*)
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE GRADE >= 3;

--SELECT ENAME, GRADE
--FROM EMP E
--INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
--WHERE GRADE >= 3;

-- 5. 81년도에 입사한 사람들을 모두 출력하시오.
SELECT *
FROM EMP
WHERE TO_CHAR(HIREDATE, 'YY') = 81;
    
-- 6. 각 직급별 가장 많은 급여를 받는 사람을 출력하시오.
SELECT ENAME, E.JOB, SAL
FROM EMP E
INNER JOIN (
    SELECT MAX(SAL) AS MAX_SAL, JOB
    FROM EMP
    GROUP BY JOB
) P ON E.SAL = MAX_SAL AND E.JOB = P.JOB;   -- JOIN도 겹치기 적용이 가능

SELECT MAX(SAL), JOB
FROM EMP
GROUP BY JOB;

-- 7. SALESMAN 직급보다 평균급여가 높은 부서들의 부서명, 평균등급을 출력하시오.
SELECT AVG(SAL), JOB
FROM EMP group by JOB
HAVING JOB = 'SALESMAN';    -- SALESMAN 부서의 평균급여

SELECT AVG(SAL), JOB
FROM EMP
GROUP BY JOB
HAVING AVG(SAL) > (
    SELECT AVG(SAL)
    FROM EMP group by JOB
    HAVING JOB = 'SALESMAN'
); -- SALESMAN 부서보다 평균급여가 높은 부서들의 부서명, 평균급여

SELECT AVG(GRADE)
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE E.JOB = 'SALESMAN';   -- SALESMAN 부서의 평균등급

SELECT ROUND(AVG(GRADE), 1), JOB
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY JOB
HAVING AVG(SAL) > (
    SELECT AVG(SAL)
    FROM EMP group by JOB
    HAVING JOB = 'SALESMAN'
); -- SALESMAN 부서보다 평균급여가 높은 부서들의 부서명, 평균등급
