SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;

-- EX) 사원명, 직급, 부서명, 부서위치를 출력
SELECT ENAME AS 사원명, JOB AS 직급, DNAME AS 부서명, LOC AS 부서위치
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

-- EX) 사원번호, 사원명, 급여, 급여등급을 출력
SELECT EMPNO, ENAME, SAL, LOSAL, HISAL, GRADE
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL; -- 범위의 컬럼값을 JOIN 할 수 있다.

-- EX) 각 직급별 급여의 평균등급
SELECT ROUND(AVG(GRADE), 1), JOB
FROM SALGRADE S
INNER JOIN EMP E ON E.SAL BETWEEN S.LOSAL AND S.HISAL 
GROUP BY JOB;

-- EX) 부서별 급여 평균등급(부서명, 평균등급 출력)
SELECT DNAME AS 부서명, ROUND(AVG(GRADE), 1) AS 평균등급
FROM DEPT D
INNER JOIN EMP E ON E.DEPTNO = D.DEPTNO
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
GROUP BY DNAME;



