SELECT *
FROM PROFESSOR;
SELECT *
FROM DEPARTMENT;
SELECT *
FROM STU;

-- EX) 공과대학에 속한 학과를 모두 출력
--SELECT DNAME
--FROM DEPARTMENT 
--WHERE PART IN(100, 200);

SELECT * 
FROM DEPARTMENT D1
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO;

SELECT D1.DNAME
FROM DEPARTMENT D1
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
WHERE D3.DNAME = '공과대학';


-- EX) 공과대학에 속한(전공이 공과대학만) 학생의 목록을 출력하세요
-- 1) 학생들의 학과 출력
SELECT S.NAME, D.DNAME
FROM STU S
INNER JOIN DEPARTMENT D ON S.DEPTNO1 = D.DEPTNO;

-- 2) 학생들의 학과, 학부까지 출력
SELECT S.NAME, D1.DNAME, D1.PART, D2.DNAME
FROM STU S
INNER JOIN DEPARTMENT D1 ON S.DEPTNO1 = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO;

-- 3) 학생들의 대학까지 출력
SELECT S.NAME, D1.DNAME, D1.PART, D2.DNAME, D3.DNAME
FROM STU S
INNER JOIN DEPARTMENT D1 ON S.DEPTNO1 = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO;

-- 4) 공과대학 학생 목록
SELECT S.NAME AS 학생명, D1.DNAME AS 전공학과, D2.DNAME, D3.DNAME
FROM DEPARTMENT D1
INNER JOIN STU S ON D1.DEPTNO = S.DEPTNO1
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
WHERE D3.DNAME = '공과대학';


-- EX) 인문대학에 속한 교수 
SELECT P.NAME, P.POSITION, D3.DNAME
FROM PROFESSOR P
INNER JOIN DEPARTMENT D1 ON P.DEPTNO = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D2.DEPTNO = D1.PART
INNER JOIN DEPARTMENT D3 ON D3.DEPTNO = D2.PART
WHERE D3.DNAME = '인문대학';


-- EX) JUMIN 컬럼을 이용해서 남자 OR 여자인지 판별
SELECT NAME,
    CASE WHEN SUBSTR(JUMIN, 7, 1) IN (1,3) THEN '남자'    -- SUBSTR(JUMIN, 7, 1) : 'JUMIN' 컬럼의 인덱스 7번째부터 1개의 문자
         ELSE '여자'
    END 성별
FROM STU;