-- TRIGGER 트리거
CREATE OR REPLACE TRIGGER TRIGGER_TEST1
    BEFORE -- AFTER
    UPDATE ON DEPT
    FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('변경 전 : ' || :OLD.DNAME);
    DBMS_OUTPUT.PUT_LINE('변경 전 : ' || :NEW.DNAME);
END;
/

SET SERVEROUTPUT ON;
UPDATE DEPT
SET 
    DNAME = 'TEST'
WHERE
    DEPTNO = 10;
    
-- EX
CREATE OR REPLACE TRIGGER TRIGGER_TEST2
    BEFORE
    INSERT ON EMP
    FOR EACH ROW
DECLARE  -- TRIGGER는 'DECLARE'로 변수선언
    SALAVG EMP.SAL%TYPE;
BEGIN
    SELECT ROUND(AVG(SAL), 0)
    INTO SALAVG
    FROM EMP;
    DBMS_OUTPUT.PUT_LINE('급여 평균 : ' || SALAVG);
END;
/

INSERT INTO EMP(EMPNO, ENAME, JOB, HIREDATE, SAL)
    VALUES(1001, 'TEST', 'SALES', SYSDATE, 1234);
    
    

?
