CREATE OR REPLACE TRIGGER EMP_TRIGGER1
    AFTER
    INSERT OR UPDATE OR DELETE ON EMP
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO EMP_LOG
        VALUES (:NEW.EMPNO, :NEW.MGR, :NEW.SAL, :NEW.COMM, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'I');
    ELSIF UPDATING THEN
        INSERT INTO EMP_LOG
        VALUES (:NEW.EMPNO, :NEW.MGR, :NEW.SAL, :NEW.COMM, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'U');
    ELSIF DELETING THEN
        RAISE_APPLICATION_ERROR(-20000, 'EMP 테이블은 삭제 불가');
    END IF;
END;
/
-- 오류번호로 지정할 수 있는 범위 : -20000 ~ -29999 
DELETE FROM EMP WHERE EMPNO = 7369;



/* EMP 테이블의 데이터를 주말(토, 일)에는 삭제 x */
-- TO_CHAR(SYSDATE 'DY')
CREATE OR REPLACE TRIGGER EMP_TRIGGER2
    AFTER
    DELETE ON EMP
    FOR EACH ROW
BEGIN
    IF TO_CHAR(SYSDATE, 'DY') IN ('수', '토', '일') THEN
        RAISE_APPLICATION_ERROR(-20000, '주말에는 삭제 불가');
    END IF;
END;
/
